- id: '1604398438605'
  alias: Kodi ON
  description: WOL for Kodi/ht
  trigger:
  - platform: device
    device_id: 610575461bdb0c78b5292ed50cb4add2
    domain: kodi
    entity_id: media_player.kodi
    type: turn_on
  condition: []
  action:
  - service: media_player.select_source
    data:
      entity_id: media_player.shield
      source: Kodi
  mode: single
- id: '1604398977874'
  alias: Kodi OFF
  description: ''
  trigger:
  - platform: device
    device_id: 610575461bdb0c78b5292ed50cb4add2
    domain: kodi
    entity_id: media_player.kodi
    type: turn_off
  condition: []
  action:
  - service: media_player.select_source
    data:
      entity_id: media_player.shield
      source: Android TV Launcher
  mode: single
- id: '1647434912320'
  alias: Telegram garage activation notification
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.telegram_command_garage_door
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      target: -188664497
      message: Garage door control enabled
  mode: single
