#- platform: command_line
#  name: kodi
#  command: "(ping -c3 -W2 -w8 ht > /dev/null 2>&1 && echo ON) || echo OFF"
#  device_class: connectivity
#  #scan_interval: 5
#  scan_interval: 11
#- platform: command_line
#  name: xbox360
#  command: "(ping -c3 -W2 -w8  > /dev/null 2>&1 && echo ON) || echo OFF"
#  device_class: connectivity
#  #scan_interval: 5
#  scan_interval: 10
#- platform: command_line
#  name: ps3
#  command: "(ping -c3 -W2 -w8 ps3 > /dev/null 2>&1 && echo ON) || echo OFF"
#  device_class: connectivity
#  #scan_interval: 5
#  scan_interval: 9


- platform: command_line
  name: ps5
  command: /config/sensors/ps5.py -b -q ps5
  scan_interval: 10


#- platform: command_line
#  name: dummy
#  command: "cat /config/dummysensor"
#  scan_interval: 5


