#- platform: yr
#- platform: command_line
#  name: kodi
#  command: "(ping -c3 -W2 -w8 ht > /dev/null 2>&1 && echo ON) || echo OFF"
#  device_class: connectivity
#  #scan_interval: 5
#  scan_interval: 11
#- platform: command_line
#  name: xbox360
#  command: "(ping -c3 -W2 -w8 xbox-360 > /dev/null 2>&1 && echo ON) || echo OFF"
#  device_class: connectivity
#  #scan_interval: 5
#  scan_interval: 10
#- platform: command_line
#  name: ps3
#  command: "(ping -c3 -W2 -w8 ps3 > /dev/null 2>&1 && echo ON) || echo OFF"
#  device_class: connectivity
#  #scan_interval: 5
#  scan_interval: 9
- platform: command_line
  name: ps4
  command: /config/sensors/ps4.py
  device_class: connectivity
  scan_interval: 10

- platform: mqtt
  name: cam_01_motion
  state_topic: "emqtt/cam-01unts.se"
  device_class: motion
  #value_template: '{% if as_timestamp(now()) - value|int < 20 %}ON{% else %}OFF{% endif %}'
  #value_template: 'ON'


- platform: command_line
  name: dummy
  command: "cat /config/dummysensor"
  scan_interval: 5
