- platform: mqtt
  object_id: "room_temp"
  name: "Room temp"
  modes:
    - 'off'
    - 'heat'
  current_temperature_topic: "+/HP/0203"
  temperature_state_topic: "+/HP/0203"
  temperature_command_topic: "8cce4efdacab/HP/SET/0203"
  action_topic: "+/HP/1A01"
  action_template: "{{ 'heating' if value == '1' else 'off' }}"
  min_temp: 13
  max_temp: 26
  temp_step: .1


