homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret location_lat
  longitude: !secret location_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 19
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

  external_url: "https://ha.unts.se"
  internal_url: "http://192.168.0.2:8123"

  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

my:

# Discover some devices automatically
#discovery:

mobile_app:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

recorder:
  db_url: !secret db_url
  purge_keep_days: 90


# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - media_player
      - device_tracker
      - input_number
      - number

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
    entity_globs:
      - sensor.wicphone_*
      - sensor.s21_*
      - sensor.bl_wic_*

# Track the sun
sun:

# Text to speech
#tts:
#  platform: google_translate

logger:
  default: warning
  logs:
    #homeassistant.components.automation: debug
    #homeassistant.components.google_assistant: debug
    #homeassistant.components.python_script: debug
    #homeassistant.components.media_player: debug
    #homeassistant.components.media_player.kodi: info
    #homeassistant.components.switch.broadlink: debug
    #homeassistant.components.xiaomi_aqara: debug
    #homeassistant.components.mqtt: debug
    #homeassistant.components.light: debug
    #homeassistant.components.logbook: debug
    #pydeconz: debug
    #homeassistant.components.deconz: debug
    #homeassistant.components.device_tracker: debug
    #homeassistant.components.unifi: debug
    #homeassistant.components.device_tracker.unifi: debug
    homeassistant.components.telegram_bot: debug
    custom_components.spotcast: debug
    #custom_components.nordpool: debug
    #custom_components.nordpool.sensor: debug
    #custom_components.nordpool.aio_price: debug
    homeassistant.components.tibber: debug

python_script:

wake_on_lan:

mqtt_eventstream:
  publish_topic: homeassistant/events

alarm_control_panel:
  - platform: manual

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

group: !include groups.yaml
switch: !include switches.yaml
light: !include lights.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
media_player: !include media_players.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_numbers.yaml
input_text: !include input_text.yaml
camera: !include cameras.yaml
#notify: !include notify.yaml
timer: !include timers.yaml
google_assistant: !include google_assistant.yaml
telegram_bot: !include telegram_bot.yaml
lock: !include locks.yaml
shell_command: !include shell_commands.yaml
template: !include template.yaml
mqtt: !include mqtt.yaml
utility_meter: !include utility_meters.yaml
