homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret location_lat
  longitude: !secret location_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 19
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

  external_url: "https://ha.unts.se"
  internal_url: "http://192.168.0.2:8123"

  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
#discovery:

mobile_app:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time.
history:
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - media_player
      - device_tracker
      - updater

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
    entity_globs:
      - sensor.mi_6*

# Track the sun
sun:

# Text to speech
#tts:
#  platform: google_translate

logger:
  default: warning
  logs:
    #homeassistant.components.automation: debug
    #homeassistant.components.google_assistant: debug
    #homeassistant.components.python_script: debug
    #homeassistant.components.media_player: debug
    #homeassistant.components.media_player.kodi: info
    #homeassistant.components.switch.broadlink: debug
    #homeassistant.components.xiaomi_aqara: debug
    #homeassistant.components.mqtt: debug
    #homeassistant.components.light: debug
    #homeassistant.components.logbook: debug
    #PyXiaomiGateway: debug
    #homeassistant.components.zwave: info
    #pydeconz: debug
    #homeassistant.components.deconz: debug
    #homeassistant.components.device_tracker: debug
    #homeassistant.components.unifi: debug
    #homeassistant.components.device_tracker.unifi: debug
    homeassistant.components.telegram_bot: debug

python_script:
wake_on_lan:
mqtt:
  broker: localhost
  username: !secret mqtt_username
  password: !secret mqtt_password

#xiaomi_aqara:
#  discovery_retry: 5
#  gateways:
#    - host: '192.168.0.127'
#      key: !secret xiaomi_key

zwave:
  usb_path: /dev/zwave
  # debug: true
  network_key: !secret zwave_network_key 
  #device_config_glob:
    #"sensor.in_wall_switch*":
    #    ignored: true
    #"zwave.*":
    #    ignored: true

alarm_control_panel:
  - platform: manual


#unifi:
#  controllers:
#    - host: localhost
#      #username: !secret unifi_username
#      #password: !secret unifi_password
#      verify_ssl: false
#      interval_seconds: 8
#      consider_home: 60

surepetcare:
  username: !secret surepet_username
  password: !secret surepet_password
  #household_id: 52500
  flaps: [159199]
  pets: [80671, 80672]

influxdb: !include influxdb.yaml
group: !include groups.yaml
switch: !include switches.yaml
light: !include lights.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
media_player: !include media_players.yaml
cast: !include cast.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_numbers.yaml
input_text: !include input_text.yaml
camera: !include cameras.yaml
notify: !include notify.yaml
timer: !include timers.yaml
google_assistant: !include google_assistant.yaml
telegram_bot: !include telegram_bot.yaml
lock: !include locks.yaml
shell_command: !include shell_commands.yaml
