version: "3.6"
services:
  ha:
    image: homeassistant/home-assistant:stable
    container_name: ha
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/app/homeassistant:/config 
    devices:
      - /dev/zwave
