- platform: mqtt
  name: Power usage
  state_topic: "power_meter/power"
  unit_of_measurement: W
  value_template: '{{ value | int }}'
- platform: influxdb
  scan_interval: 300
  queries:
    - name: temperature_darksky
      database: telegraf
      measurement: temperature
      group_function: last
      where: 'friendly_name = ''Outside'''
      unit_of_measurement: '°C'
- platform: template
  sensors:
    tv_time:
      friendly_name: "TV Time"
      #entity_id: media_player.sony_bravia_tv
      value_template: "{{ ((now() - states.media_player.sony_bravia_tv.last_changed).total_seconds()/60)|round(0) }}"
      unit_of_measurement: 'minutes'
  #scan_interval: 30
