- platform: mqtt
  name: Power usage
  state_topic: "power_meter/power"
  unit_of_measurement: W
  value_template: '{{ value | int }}'
  device_class: power

  #- platform: command_line
  #  name: Twinkly sensor
  #  command: >
  #    /config/scripts/twinkly.py 192.168.0.41 get_color get_brightness get_mode
  #  scan_interval: 10
  #  value_template: "{{ value_json.get_mode }}"
  #  json_attributes:
  #    - get_color
  #    - get_brightness
  #    - get_mode

- platform: mqtt
  object_id: hp_rad_forward
  name: "Rad Forward"
  state_topic: "+/HP/0002"
  device_class: temperature
  unit_of_measurement: "°C"
- platform: mqtt
  object_id: hp_heat_carrier_return
  name: "Heat Carrier Return"
  state_topic: "+/HP/0003"
  device_class: temperature
  unit_of_measurement: "°C"    
- platform: mqtt
  object_id: hp_heat_carrier_forward
  name: "Heat Carrier Forward"
  state_topic: "+/HP/0004"
  device_class: temperature
  unit_of_measurement: "°C"
- platform: mqtt
  object_id: hp_brine_in
  name: "Brine In"
  state_topic: "+/HP/0005"
  device_class: temperature
  unit_of_measurement: "°C"
- platform: mqtt
  object_id: hp_brine_out
  name: "Brine Out"
  state_topic: "+/HP/0006"
  device_class: temperature
  unit_of_measurement: "°C"
- platform: mqtt
  object_id: hp_outdoor
  name: "Outdoor"
  state_topic: "+/HP/0007"
  device_class: temperature
  unit_of_measurement: "°C"
- platform: mqtt
  object_id: hp_warm_water
  name: "Warm water"
  state_topic: "+/HP/0009"
  device_class: temperature
  unit_of_measurement: "°C"
- platform: mqtt
  object_id: hp_hot_gas
  name: "Hot gas"
  state_topic: "+/HP/000B"
  device_class: temperature
  unit_of_measurement: "°C"
- platform: mqtt
  object_id: hp_additional_electric_heater
  name: "Additional electric heater"
  state_topic: "+/HP/3104"
  device_class: temperature
  unit_of_measurement: "%"
  icon: mdi:flash
