- platform: mqtt
  name: Power usage
  state_topic: "power_meter/power"
  unit_of_measurement: W
  value_template: '{{ value | int }}'
- platform: influxdb
  scan_interval: 300
  queries:
    - name: temperature_darksky
      database: telegraf
      measurement: temperature
      group_function: last
      where: 'friendly_name = ''Outside'''
      unit_of_measurement: '°C'
- platform: command_line
  name: TV today
  command: /config/sensors/tv_time.py
  unit_of_measurement: minutes
  scan_interval: 60
- platform: command_line
  name: TV last session
  friendly_name: TV Time last session
  command: /config/sensors/tv_time.py last_session
  unit_of_measurement: minutes
  scan_interval: 60
