#- platform: command_line
#  switches:
    #cinema_ventilation:
    #  command_on: 'cd /config; password=$(./get_secret.py cinema_vent_password) ./switches/cinema_ventilation.py True'
    #  command_off: 'cd /config; password=$(./get_secret.py cinema_vent_password) ./switches/cinema_ventilation.py False'
    #  command_state: 'cd /config; password=$(./get_secret.py cinema_vent_password) ./switches/cinema_ventilation.py | grep True'
    #  friendly_name: Ventilation
    #garage_door_raw:
    #  command_on: 'cd /config; password=$(./get_secret.py garage_door_password) ./switches/garage_door.py'
    #  command_off: 'cd /config; password=$(./get_secret.py garage_door_password) ./switches/garage_door.py && sleep 10'
    #  command_state: ':'
    #  # off = false = closed, on = true = open
    #  value_template: "{{ is_state('binary_sensor.openclose_1', 'on') }}"
      

- platform: broadlink
  mac: '34:EA:34:40:7C:D0'
  switches:
    - name: Projector
      # Sanyo PLV-Z3000 discrete off wasn't easy to find!
      command_on: 'JgBoAAABKZAVNRU0Fg8VEBYzFjQVEBUQFRAVEBUQFRAVEBYPFg8WDxUQFg8WDxUQFhAVEBUQFRAUNRU0FTQWNBU0FTQWMxY0FQAFpwABKEgVAAxFAAEpRxUADEUAAShIFQAMRQABKEgUAA0F'
      command_off: 'JgBQAAABKJQSOBI4EhMSExI4EjgSExITEhMSExITEhMSExITEhMSExI4EhMSExITEhMSOBITEjgSExI4EjgSOBI4EhMSOBITEgAFpAABKEoSAAyWDQUAAAAAAAA='

- platform: template
  switches:
    #garage_door:
    #  friendly_name: Garage door
    #  turn_on:
    #    # cancel it if it's already running
    #    - service: script.turn_off
    #      entity_id: script.garage_door
    #    - service: script.garage_door
    #  turn_off:
    #    # cancel it if it's already running
    #    - service: script.turn_off
    #      entity_id: script.garage_door
    #    - service: script.garage_door
    #  value_template: "{{ is_state('binary_sensor.openclose_1', 'on') }}"
    garage_door:
      friendly_name: Garage door
      turn_on:
        - service: script.garage_door_trigger
      turn_off:
        - service: script.garage_door_trigger
      value_template: "{{ is_state('binary_sensor.openclose_1', 'on') }}"


- platform: mqtt
  object_id: hp_external_control_1
  name: "External control 1"
  state_topic: "+/HP/2233"
  command_topic: "8cce4efdacab/HP/SET/2233"
  payload_on: "1.00"
  payload_off: "0.00"
  optimistic: false

- platform: mqtt
  object_id: hp_external_control_2
  name: "External control 2"
  state_topic: "+/HP/2234"
  command_topic: "8cce4efdacab/HP/SET/2234"
  payload_on: "1.00"
  payload_off: "0.00"
  optimistic: false

