- platform: command_line
  switches:
    #cinema_ventilation:
    #  command_on: 'cd /config; password=$(./get_secret.py cinema_vent_password) ./switches/cinema_ventilation.py True'
    #  command_off: 'cd /config; password=$(./get_secret.py cinema_vent_password) ./switches/cinema_ventilation.py False'
    #  command_state: 'cd /config; password=$(./get_secret.py cinema_vent_password) ./switches/cinema_ventilation.py | grep True'
    #  friendly_name: Ventilation
    # omg rebuild this plz
    living_room_receiver:
      command_on: 'cd /config; password=$(./get_secret.py living_room_receiver_password) ./switches/living_room_receiver.py False'
      command_off: 'cd /config; password=$(./get_secret.py living_room_receiver_password) ./switches/living_room_receiver.py True'
      command_state: 'cd /config; password=$(./get_secret.py living_room_receiver_password) ./switches/living_room_receiver.py | grep False > /dev/null'
      friendly_name: Stereo
    garage_door_raw:
      command_on: 'cd /config; password=$(./get_secret.py garage_door_password) ./switches/garage_door.py'
      command_off: 'cd /config; password=$(./get_secret.py garage_door_password) ./switches/garage_door.py && sleep 10'
      # off = false = closed, on = true = open
      value_template: "{{ is_state('binary_sensor.openclose_1', 'on') }}"
      

- platform: broadlink
  host: 'rm-mini'
  mac: '34:EA:34:40:7C:D0'
  friendly_name: RMMini3
  switches:
    projector:
      friendly_name: Projector
      command_on: 'JgBoAAABKZAVNRU0Fg8VEBYzFjQVEBUQFRAVEBUQFRAVEBYPFg8WDxUQFg8WDxUQFhAVEBUQFRAUNRU0FTQWNBU0FTQWMxY0FQAFpwABKEgVAAxFAAEpRxUADEUAAShIFQAMRQABKEgUAA0F'
      command_off: 'JgBQAAABKJQSOBI4EhMSExI4EjgSExITEhMSExITEhMSExITEhMSExI4EhMSExITEhMSOBITEjgSExI4EjgSOBI4EhMSOBITEgAFpAABKEoSAAyWDQUAAAAAAAA='

- platform: template
  switches:
    garage_door:
      friendly_name: Garage door
      turn_on:
        # cancel it if it's already running
        - service: script.turn_off
          entity_id: script.garage_door
        - service: script.garage_door
      turn_off:
        # cancel it if it's already running
        - service: script.turn_off
          entity_id: script.garage_door
        - service: script.garage_door
      value_template: "{{ is_state('binary_sensor.openclose_1', 'on') }}"

