- alias: 'Arm alarm when noone home'
  trigger:
    - platform: state
      entity_id: group.family
      to: not_home
      #for:
      #  minutes: 10
  condition: 
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: disarmed
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.all
      data_template:
        title: 'Arming alarm'
        message: "No one home at {{ now().strftime('%H:%M') }}"
      data:
        data:
          #tag: arming
          actions:
            - action: disarm_alarm
              title: Disarm

- alias: 'Abort alarm arming'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: disarm_alarm
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm
    - service: logbook.log
      data_template:
        name: 'Aborted arming'
    
- alias: 'Disarm alarm when someone comes home'
  trigger:
    - platform: state
      entity_id: group.family
      to: 'home'
    - platform: state
      entity_id: switch.garage_door_raw
      to: 'on'
  condition:
    - condition: template
      value_template: '{{ states("alarm_control_panel.ha_alarm") != "disarmed" }}'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.all
      data_template:
        title: 'Disarming alarm'
        # TODO: who?
        message: "Someone came home at {{ now().strftime('%H:%M') }}"

- alias: 'Trigger alarm'
  trigger:
    - platform: state
      entity_id: group.alarm
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: input_text.set_value
      data_template:
        entity_id: input_text.triggered_alarm_entities
        value: |
          {%- for entity in states.group.alarm.attributes.entity_id if states(entity) == 'on' %}
          * {{ state_attr(entity, 'friendly_name') -}}
          {% endfor %}

- alias: 'Notify alarm triggered'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'triggered'
  action:    
    - service: notify.all
      data_template:
        title: 'Alarm triggered'
        message: >
          Triggered sensors:
          {{ states('input_text.triggered_alarm_entities') }}
    # Clear variable
    - service: input_text.set_value
      data:
        entity_id: input_text.triggered_alarm_entities
        value: ''

- alias: 'Motion outside basement door triggers light inside'
  trigger:
      # Basement door motion
      platform: state
      entity_id: binary_sensor.motion_2
      to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_away
  action:
    - delay: '00:00:{{ range(12, 30)|random|int }}'
    - service: switch.turn_on
      entity_id: switch.in_wall_7
    - delay: '00:0{{ range(0, 3)|random|int }}:{{ range(20, 40)|random|int }}'
    - service: switch.turn_off
      entity_id: switch.in_wall_7

- alias: 'Motion outside back door triggers light inside'
  # need new light for this
  initial_state: 'off'
  trigger:
      # Back door motion
      platform: state
      entity_id: binary_sensor.motion_1
      to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_away
  action:
    - delay: '00:00:{{ range(12, 30)|random|int }}'
    - service: homeassistant.turn_on
      entity_id: switch.plug_3
    - delay: '00:0{{ range(0, 3)|random|int }}:{{ range(20, 40)|random|int }}'
    - service: homeassistant.turn_off
      entity_id: switch.plug_3

# More of a reminder than an alarm maybe..
- alias: 'Garage door left open'
  trigger:
    # Garage door
    platform: state
    entity_id: binary_sensor.openclose_1
    to: 'on'
    for:
      minutes: 15
  condition:
    condition: state
    entity_id: group.family
    state: not_home
  action:
    service: notify.all
    data_template:
      title: 'Garage door open'
      message: "It's been open for 15 mins..."

- alias: 'Alarm auto on if noone home'
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: disarmed
    - condition: state
      entity_id: group.family
      state: not_home
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.all
      data_template:
        title: 'Arming alarm'
        message: "No one home and it's {{ now().strftime('%H:%M') }}"
      data:
        data:
          tag: arming
          actions:
            - action: disarm_alarm
              title: Disarm

- alias: 'Alarm auto off'
  initial_state: 'off'
  trigger:
    platform: time
    at: '06:30:00'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.all
      data_template:
        title: 'Disarming alarm'
        message: "At {{ now().strftime('%H:%M') }}"

