- alias: 'Axels room secondary lights'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: 'button_2'
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: 'button_4'
        event: 1002
  action:
    service: switch.toggle
    data:
      entity_id: switch.zb_plug_7

- alias: 'Axels button long press on'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: 'button_4'
      event: 1001
  condition:
    condition: state
    entity_id: switch.zb_plug_7
    state: 'off'
  action:
    # Axels secondary
    - service: homeassistant.turn_on
      data:
        entity_id: switch.zb_plug_7
    # Bathroom
    - service: light.turn_on
      data:
        entity_id: light.zb_in_wall_1
        brightness_pct: 15
    # Office secondary
    - service: homeassistant.turn_on
      data:
        entity_id: switch.plug_1

- alias: 'Axels button long press off'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: 'button_4'
      event: 1001
  condition:
    condition: state
    entity_id: switch.zb_plug_7
    state: 'on'
  action:
    # Axels secondary
    - service: homeassistant.turn_off
      data:
        entity_id: switch.zb_plug_7
    # Bathroom
    - service: light.turn_off
      data:
        entity_id: light.zb_in_wall_1
    # Office secondary
    - service: homeassistant.turn_off
      data:
        entity_id: switch.plug_1

