- alias: 'Axels room secondary lights'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: 'button_2'
      event: 1000
  action:
    service: switch.toggle
    data:
      entity_id: switch.in_wall_4
