- alias: 'Bathroom lights trigger'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_4
    to: 'on'
  condition:
    - condition: state
      entity_id: light.zb_in_wall_1
      state: 'off'
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: -4
  action:
    service: light.turn_on
    data:
      entity_id: light.zb_in_wall_1
      brightness_pct: 16

      #brightness_pct: >
      #  {% if states('sensor.motion_4_light')|int < 5 %}
      #    16
      #  {% elif states('sensor.motion_4_light')|int < 10 %}
      #    33
      #  {% else %}
      #    62
      #  {% endif %}

- alias: 'Bathroom lights auto off'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_4
    to: 'off'
    for:
      minutes: 15
  action:
    service: light.turn_off
    data:
      entity_id: light.zb_in_wall_1
