- alias: 'Ventilate for max 2h'
  trigger:
    platform: state
    entity_id: switch.zb_plug_2
    to: 'on'
    for:
      minutes: 120
  action:
    service: homeassistant.turn_off
    entity_id: switch.zb_plug_2
 
- alias: 'Ventilate for max 6h'
  trigger:
    platform: state
    entity_id: light.in_wall_2
    to: 'on'
    for:
      hours: 6
  action:
    service: homeassistant.turn_off
    entity_id: light.in_wall_2

- alias: 'Sub auto on'
  trigger:
    - platform: state
      entity_id: media_player.denon_3300
      to: 'on'
    - platform: state
      entity_id: media_player.denon_3300
      to: 'playing'
  action:
    service: homeassistant.turn_on
    entity_id: switch.plug_2

- alias: 'Sub auto off'
  trigger:
    platform: state
    entity_id: media_player.denon_3300
    to: 'off'
    for:
      minutes: 7
  action:
    service: homeassistant.turn_off
    entity_id: switch.plug_2

- alias: 'Receiver max 5h'
  trigger:
    platform: state
    entity_id: media_player.denon_3300
    to: 'on'
    for:
      hours: 5
  action:
    service: homeassistant.turn_off
    entity_id: media_player.denon_3300


