- alias: Garage light trigger
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.motion_3
        - binary_sensor.openclose_1
      to: 'on'
  condition:
    condition: state
    entity_id: switch.in_wall_1
    state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.in_wall_1

- alias: Garage lights motion timeout
  trigger:
      platform: state
      entity_id: binary_sensor.motion_3
      to: 'off'
      for: '00:02:00'
  condition:
    condition: state
    entity_id: switch.in_wall_1
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.in_wall_1

- alias: Garage door telegram command auto disable
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'armed_away'
    - platform: time
      at: '00:00:00'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.telegram_command_garage_door


- alias: 'Enable telegram integration'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: garage_enable_telegram_integration
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.telegram_command_garage_door

- alias: 'Trigger garage door'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: garage_door_trigger
  action:
    - service: homeassistant.toggle
      entity_id: script.garage_door_trigger
    # TODO: telegram chat response
