- alias: Garage lights motion trigger
  trigger:
      platform: state
      #entity_id: group.garage_motion_sensors
      entity_id: binary_sensor.motion_3
      to: 'on'
  condition:
    condition: state
    entity_id: switch.in_wall_1
    state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.in_wall_1

- alias: Garage lights motion timeout
  trigger:
      platform: state
      #entity_id: group.garage_motion_sensors
      entity_id: binary_sensor.motion_3
      to: 'off'
      for: '00:02:00'
  condition:
    condition: state
    entity_id: switch.in_wall_1
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.in_wall_1

- alias: Garage door auto lock
  trigger:
    - platform: state
      entity_id: input_boolean.garage_door_lock
      to: 'off'
      for: '3:00:00'
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'armed_away'
    - platform: time
      at: '00:00:00'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.garage_door_lock

- alias: Garage door telegram command auto disable
  trigger:
    - platform: state
      entity_id: input_boolean.telegram_command_garage_door
      to: 'on'
      for: '3:00:00'
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'armed_away'
    - platform: time
      at: '00:00:00'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.telegram_command_garage_door
