- alias: Update notification
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.html5
    data_template: 
      title: 'New Home Assistant Release'
      message: "Home Assistant  {{ states.updater.updater.state }}  is now available."
