- alias: 'Living room receiver auto on'
  trigger:
    - platform: state
      entity_id: media_player.vardagsrum__stereo
      to: 'playing'
    - platform: state
      entity_id: media_player.sony_bravia_tv
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.living_room_receiver 

- alias: 'Living room receiver auto off'
  trigger:
    - platform: state
      entity_id: media_player.vardagsrum__stereo
      to: 'off'
      for:
        minutes: 1
    - platform: state
      entity_id: media_player.sony_bravia_tv
      to: 'off'
      for:
        seconds: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.vardagsrum__stereo
        state: 'off'
      - condition: state
        entity_id: media_player.sony_bravia_tv
        state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.living_room_receiver 

