- alias: 'Living room receiver auto on'
  trigger:
    - platform: state
      entity_id: media_player.living_room_stereo
      to: 'playing'
    - platform: state
      entity_id: media_player.sony_bravia_tv
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.zb_plug_6
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.zb_plug_6

- alias: 'Living room receiver auto off'
  trigger:
    - platform: state
      entity_id: media_player.living_room_stereo
      to: 'off'
      for:
        minutes: 2
    - platform: state
      entity_id: media_player.sony_bravia_tv
      to: 'off'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: media_player.living_room_stereo
      state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.zb_plug_6

#- alias: 'Christmas lights random color'
#  initial_state: 'on'
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: 'button_3'
#      event: 1002 # normal release
#  action:
#    - service: script.twinkly_random_color
#
#- alias: 'Christmas lights vanilla'
#  initial_state: 'on'
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: 'button_3'
#      event: 1004 # double press
#  action:
#    - service: script.twinkly_vanilla

- alias: 'Twinkly effects cycle'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: 'button_3'
  condition: "{{ trigger.event.data.event in [1002, 1004] }}" # 1x or 2x press
  action:
    - service: script.twinkly_effects_cycle
      data:
        target: >
          {%- set targets = {1002: "light.twinkly2", 1004: "light.twinkly1" } %}
          {{- targets[trigger.event.data.event] }}

- alias: 'Twinkly off'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: 'button_3'
      event: 1001 # long press
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.twinkly1
          - light.twinkly2
