- alias: 'Patio lights on'
  #trigger:
    #- platform: sun
    #  event: sunset
    #  offset: "00:15:00"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      # Can be a positive or negative number
      below: -3.5
  action:
    service: homeassistant.turn_on
    entity_id: switch.in_wall_2

- alias: 'Patio lights off'
  #trigger:
  #  - platform: sun
  #    event: sunrise
  #    offset: '-00:15:00'
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      # Can be a positive or negative number
      above: -3.5
  action:
    service: homeassistant.turn_off
    entity_id: switch.in_wall_2
