- alias: 'Spotify source living room CCA'
  trigger:
    platform: template
    #entity_id: media_player.spotify
    value_template: "{{ is_state_attr('media_player.spotify', 'media_title', 'A a A a A Very Good Song') }}"
  action:
    service: media_player.select_source
    data_template:
      entity_id: media_player.spotify
      source: 'Living room'

