- alias: 'State mapper'
  mode: parallel
  trigger:
    platform: state
    entity_id:
      - switch.in_wall_2
      - light.office_secondary_lights
      - alarm_control_panel.ha_alarm
      - switch.in_wall_9
  action:
    service: python_script.state_mapper
    data:
      entity_id: "{{ trigger.entity_id }}"
      state: "{{ trigger.to_state.state }}"
      state_map:
        # patio lights -> christmas lights
        switch.in_wall_2: 
          target: switch.zb_plug_5
        # office secondary lights switch -> plug
        light.office_secondary_lights:
          target: switch.zb_plug_8
        # alarm disarmed -> unlock garage
        alarm_control_panel.ha_alarm:
          state: disarmed
          target: input_boolean.garage_door_lock
          match_service: homeassistant.turn_off
          nomatch_service: homeassistant.turn_on
        # living room secondary lights
        switch.in_wall_9:
          target:
            - switch.zb_plug_4 # left
            - switch.zb_plug_2 # right
